### ISSUE TITLE
Unequipping breaks/unsyncs replays

### ISSUE THREAD

**Issue by Konrad22** [doofus-01/wesnoth-Bad_Moon_Rising#7]
Example replay, breaks in turn 4.
[BMR3-Orcish Forces.gz](https://github.com/doofus-01/wesnoth-Bad_Moon_Rising/files/3000949/BMR3-Orcish.Forces.gz)

**Comment by doofus-01** [comment]
Yeah, this is a known issue.The Lua stuff needs to be wrapped in some "synchronize choice" thing that sounded like multiplayer code to me at the time, but it turns out replays use some MP features.  Fixing this will be a big PITA, especially since I haven't done anything with Lua recently and am rusty.

Good to have the issue logged here though, at least it will be harder to forget.

**Comment by doofus-01** [comment]
fixed by e1350619d94a16c214388fafa3e91346f4506c54 I believe.
